### ISSUE TITLE
Allow import outside top-level

### ISSUE THREAD

**Issue by pa-philos** [stellar-labs/gulp-inline-import#2]
When trying to do an import outside the top level, i get the expected `SyntaxError: 'import' and 'export' may only appear at the top level (44:1)`, which is fine. But Babel supports a loose mode, in which this theoritically should be possible.

Although it's not the perfect scenario, it's the main reason I wanted to throw an import was to inline another file contents inside a block, without having to resort to some fancy str regex/replace, which this has the potential.

Thanks for the lib!

**Comment by khalyomede** [comment]
Hi @Shirkit, thank you, you have the honor to be the first to commit an issue!

Gonna fix this by adding the property to let you monitor loose import mode from babel indead.

Also FYI, other ES6 import syntaxes like named imported will not work for the moment, gonna refactor the code to make something more versatile.

**Comment by khalyomede** [comment]
@Shirkit the option have been added, but I could not reproduce the issue, nor in an another PC. Please reopen this issue if it did not fixed the issue, thank you.

**Comment by pa-philos** [comment]
Hello @khalyomede 

Wow, thanks for the quick update! You totally helped me solving a very specific issue in my env.

And I'm glad to fire the first issue! It's so nice to see people working on open source projects that so fast gets visibility and helps other people, this is so "webby" 🌐 😄 

Thanks a lot, I'll test it up on monday, since I don't have access to the code right now.

Thanks again!

**Comment by khalyomede** [comment]
Hi @Shirkit, that is why we open source, to have awesome backers like you ;) Thank you for the time to open an issue and propose enhancements! Let me know if everything is fine :)
